accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

     path('login/',
          auth_views.LoginView.as_view(template_name='login.html'),
          name='login'
          ),
     path ('logout/',
          auth_views.LogoutView.as_view(template_name='logout.html'),
          name='logout'
          ),

     
]

kouka2project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('strategy.urls')),
    path('', include('accounts.urls')),


    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name = "password_reset.html"),
        name ='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name = "password_reset_sent.html"),
        name ='password_reset_done'),
    path('reset/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(
            template_name = "password_reset_form.html"),
        name ='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name = "password_reset_done.html"),
        name ='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

strategy/urls.py
from django.urls import path
from . import views

app_name = 'strategy'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('post/', views.CreatePhotoView.as_view(), name='post'),

    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),

    path('strategys/<int:category>/',
         views.CategoryView.as_view(),
         name = 'strategys_cat'),

    path('user-list/<int:user>/',
         views.UserView.as_view(),
         name = 'user_list'),
    
    path('strategy-detail/<int:pk>/',
         views.DetailView.as_view(),
         name = 'strategy_detail'),

    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    path('strategy/<int:pk>/delete/',
         views.StrategyDeleteView.as_view(),
         name = 'strategy_delete'
         ),

     path('strategy/<int:pk>/update/',
         views.StrategyUpdateView.as_view(),
         name = 'strategy_update'
         ),
     path(
        'contact/',
        views.ContactView.as_view(),
        name = 'contact'
          ),

     path('strategy-detail/<int:pk>/comment/create/', 
          views.CommentCreate.as_view(), 
          name='comment_create'
          ),
     

     path('strategy-detail/<int:pk>/comment/delete/',
         views.CommentDeleteView.as_view(),
         name = 'comment_delete'
         ),

     path('strategy-detail/<int:pk>/comment/update/',
         views.CommentUpdateView.as_view(),
         name = 'comment_update'
         ),
]

strategy/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20
    )
    
    def __str__(self):
        return self.title

class StrategyPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )
    
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )
    
    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
    )
    
    strategy = models.TextField(
        verbose_name='攻略方法',
    )
    
    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to='photos'
    )
    
    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to='photos',
        blank=True,
        null=True
    )

    image3 = models.ImageField(
        verbose_name='イメージ3',
        upload_to='photos',
        blank=True,
        null=True
    )

    image4 = models.ImageField(
        verbose_name='イメージ4',
        upload_to='photos',
        blank=True,
        null=True
    )
    
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )

    def __str__(self):
        return self.title


#----------------------------------------------------------
class Comment(models.Model):
    """記事に紐づくコメント"""
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )

    text = models.TextField(
        verbose_name='本文'
    )
    target = models.ForeignKey(
        StrategyPost, 
        on_delete=models.CASCADE, 
        verbose_name='対象記事'
    )

strategy/forms.py
from django.forms import ModelForm
from .models import StrategyPost



class StrategyPostForm(ModelForm):
    class Meta:
        model = StrategyPost
        fields = ['category', 'title', 'strategy', 'image1', 'image2', 'image3', 'image4']

#------------------------------------------------------
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前')
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='件名')
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class'] = 'form-control'

        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class'] = 'form-control'

        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control'

        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control'


#--------------------------------------------------------
from .models import Comment


class CommentCreateForm(forms.ModelForm):
    """コメント投稿フォーム"""

    class Meta:
        model = Comment
        fields = ['text']

strategy/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import StrategyPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import StrategyPost
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import UpdateView
from django.views.generic import FormView
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import Comment
from .forms import CommentCreateForm  
from django.shortcuts import redirect, get_object_or_404
from datetime import datetime



class IndexView(ListView):
    template_name = 'index.html'
    queryset = StrategyPost.objects.order_by('-posted_at')
    paginate_by = 9

@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    form_class = StrategyPostForm
    template_name = "post_strategy.html"
    success_url = reverse_lazy('strategy:post_done')
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    template_name = 'post_success.html'

class CategoryView(ListView):
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs['category']
        categories = StrategyPost.objects.filter(
            category=category_id).order_by('-posted_at')
        return categories
    
class UserView(ListView):
    template_name ='index.html'
    paginate_by = 9
    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = StrategyPost.objects.filter(
            user=user_id).order_by('-posted_at')
        return user_list
    
class DetailView(DetailView):
    template_name ='detail.html'
    model = StrategyPost

#----------------------------------------------------
    def get_context_data(self, **kwargs):
        post_pk = self.kwargs['pk']
        context = super().get_context_data(**kwargs)
        # テンプレートにコメント作成フォームを渡す
        detail = get_object_or_404(StrategyPost, pk=post_pk)
        context = {
                "detail": detail,
                "comments": Comment.objects.filter(target=detail.id)   #該当記事のコメントだけを渡します。
        }
        return context

class MypageView(ListView):
    template_name ='mypage.html'
    paginate_by = 9
    def get_queryset(self):
        queryset = StrategyPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset
    
class StrategyDeleteView(DeleteView):
    model = StrategyPost
    template_name ='strategy_delete.html'
    success_url = reverse_lazy('strategy:index')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    
class StrategyUpdateView(UpdateView):
    model = StrategyPost
    template_name = 'strategy_update.html'
    fields = ['title', 'strategy']
    success_url = reverse_lazy('strategy:index')

#---------------------------------------------------

class ContactView(FormView):
    template_name ='contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('strategy:contact')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context['form'])
        return context

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']

        subject = 'お問い合わせ：{}'.format(title)

        message = \
            '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}'\
            .format(name, email, title, message)
        
        from_email = 'admin@example.com'

        to_list = ['kkr.python9999@gmail.com']

        message = EmailMessage(subject=subject,
                               body=message,
                               from_email=from_email,
                               to=to_list,
                               )
        message.send()
        messages.success(
            self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)
    
#----------------------------------------------------

class CommentCreate(CreateView):
    template_name = 'comment_form.html'
    model = Comment
    form_class = CommentCreateForm
    success_url = reverse_lazy('strategy:comment_done')

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(StrategyPost, pk=post_pk)
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.target = post
        comment.save()
        self.object = comment
        return redirect('strategy:strategy_detail', pk=post_pk)
    
    def get_context_data(self, **kwargs):    
    # def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        context['strategy'] = get_object_or_404(StrategyPost, pk=self.kwargs['pk'])
        return context


class CommentDeleteView(DeleteView):
    model = Comment
    template_name ='comment_delete.html'
    success_url = reverse_lazy('strategy:index')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)
    
        # post_pk = self.kwargs['pk']
        
        # return redirect('strategy:strategy_detail', pk=post_pk)
    
    
class CommentUpdateView(UpdateView):
    model = Comment
    template_name = 'comment_update.html'
    fields = ['text']
    success_url = reverse_lazy('strategy:index')
    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.save()
        return super().form_valid(form)

    # def form_valid(self, form):
    #     post_pk = self.kwargs['pk']
    #     post = get_object_or_404(StrategyPost, pk=post_pk)
    #     comment = form.save(commit=False)
    #     comment.user = self.request.user
    #     comment.target = post
    #     comment.save()
    #     self.object = comment
    #     return redirect('strategy:strategy_detail', pk=post_pk)
    # def get_context_data(self, **kwargs):    
    # # def post(self, request, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['strategy'] = get_object_or_404(StrategyPost, pk=self.kwargs['pk'])
    #     return context

    # def get_queryset(self):
    #     comment = StrategyPost.objects.filter(id=Comment.objects.get(id))
    #     return comment
    # def get_context_data(self, **kwargs):
    #     post_pk = self.kwargs['pk']
    #     context = super().get_context_data(**kwargs)
    #     # テンプレートにコメント作成フォームを渡す
    #     detail = get_object_or_404(StrategyPost, pk=post_pk)
    #     context = {
    #             "detail": detail,
    #             "comments": Comment.objects.filter(target=detail.id)   #該当記事のコメントだけを渡します。
    #     }
    #     return context

strategy/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}攻略情報投稿サイト{% endblock %}</title>
    <link rel="icon" type="image/x-icon"
          href="{% static 'assets/game.ico' %}" />

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      label {
        display: block;
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">気になる攻略法を見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる攻略法投稿サイトです。
                自分で考えたものであれば内容が被っていてもオッケー！
                しかし、他の方のコピーなどは認められません。
                投稿へのコメントは歓迎です！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">コンタクト</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'strategy:mypage' %}"
                       class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                       class="text-white">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="{% url 'strategy:contact' %}"
                      class="text-white">お問い合わせ</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                       <li><a href="{% url 'strategy:contact' %}"
                        class="text-white">お問い合わせ</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'strategy:index' %}"
             class="navbar-brand d-flex align-items-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              x="0px" y="0px"
              width="30" height="30"
              viewBox="0 0 172 172"
              style=" fill:#26e07f;"><g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal"><path d="M0,172v-172h172v172z" fill="none"></path><g fill="#1fb141"><path d="M21.5,21.5v129h64.5v-32.25v-64.5v-32.25zM86,53.75c0,17.7805 14.4695,32.25 32.25,32.25c17.7805,0 32.25,-14.4695 32.25,-32.25c0,-17.7805 -14.4695,-32.25 -32.25,-32.25c-17.7805,0 -32.25,14.4695 -32.25,32.25zM118.25,86c-17.7805,0 -32.25,14.4695 -32.25,32.25c0,17.7805 14.4695,32.25 32.25,32.25c17.7805,0 32.25,-14.4695 32.25,-32.25c0,-17.7805 -14.4695,-32.25 -32.25,-32.25z"></path></g></g></svg>
            <!-- <svg xmlns="http://www.w3.org/2000/svg"
                 width="20" height="20" fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 aria-hidden="true"
                 class="me-2"
                 viewBox="0 0 24 24">
                 <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                 <circle cx="12" cy="13" r="4"/></svg> -->
            <!-- リンクテキスト-->
            <strong>攻略情報一覧</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'strategy:index' %}">トップに戻る</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          攻略情報投稿サイトは &copy; Bootstrapを使用しています。</p>
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

strategy/templates/comment_form.html
{% extends 'base.html' %}
{% block title %}コメント投稿フォーム{% endblock %}
{% block contents %}

  <!-- 追加 -->
<div class="container">
    <div class="row">
        <div class="col offset-2">
            
            <div class="comment-form">
                <h2>コメント投稿</h2>
                <!-- コメント作成用のURLを渡す -->
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <td>{{ form.text }}</td>
                        </tr>
        
                    </table>
                    <div>
                        <button type="submit">送信</button>
                    </div>
                    
            </div>
        </div>
    </div>
</div>
{% endblock %}

strategy/templates/comment_form_success.html
{% extends 'base.html' %}
{% block title %}コメント投稿成功{% endblock %}
    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offsett-2">
                <h4>投稿が完了しました！</h4>
            </div>
        </div>
    </div>
    {% endblock %}

strategy/templates/detail.html
{% extends 'base.html' %}
{% block title %}攻略情報詳細ページ{% endblock %}
    {% block contents %}
    <br>
        <div class="container">
            <div class="row">
                <div class="col offset-3">
                    <h2>{{detail.title}}</h2>
                    <p>{{detail.strategy}}</p>
                    <br>
                    <p>{{detail.posted_at}}に投稿</p>
                    <p><img src="{{ detail.image1.url }}"></img></p>
                    {% if detail.image2 %}
                        <p><img src="{{ detail.image2.url }}"></img></p>
                    {% endif %}
                    {% if detail.image3 %}
                        <p><img src="{{ detail.image3.url }}"></img></p>
                    {% endif %}
                    {% if detail.image4 %}
                        <p><img src="{{ detail.image4.url }}"></img></p>
                    {% endif %}

                    {% if request.user == detail.user %}
                    <form method="POST">
                    <a href="{% url 'strategy:strategy_delete' detail.pk %}"
                       class="btn btn-primary my-2">削除する</a>
                    </form>
                    {% endif %}
                    {% if request.user == detail.user %}
                    <form method="POST">
                    <a href="{% url 'strategy:strategy_update' detail.pk %}"
                       class="btn btn-primary my-2">更新する</a>
                    </form>
                    {% endif %}
                    <form>
                        <div class="card-body">
                            <p class="card-text">
                            <h2>コメント</h2>
                            {% for comment in comments %}
                            <hr>
                            <h6>{{ comment.user }}</h6>
                            <div class="comment-text">
                              <h4>{{ comment.text }}</h4>
                            </div>


                            {% if request.user == detail.user %}
                            <form method="POST">
                                <a href="{% url 'strategy:comment_delete' comment.id %}"
                                    class="btn btn-primary my-2">コメントを削除する</a>
                            </form>
                            {% endif %}
                            {% if request.user == detail.user %}
                            <form method="POST">
                                <a href="{% url 'strategy:comment_update' comment.id %}"
                                    class="btn btn-primary my-2">コメントを更新する</a>
                            </form>
                            {% endif %}
                            <hr>
                            {% endfor %}
                        
                        </div>
                      <!-- 追加 -->
                        <div class="comment-form">
                            <h2>【コメント投稿】</h2>
                        <!-- コメント作成用のURLを渡す -->
                            {% if user.is_authenticated %}
                            <type="text" id="detail_id" name="detail_id" value="{{ object.id }}">
                            <a class="btn btn-success col-3" href="{% url 'strategy:comment_create' detail.id %}">コメント送信フォームはこちら</a>
                            {% else %}
                            <h4>アカウントにログインしていません、<br>
                                アカウントにログインしてからコメントが投稿できます。</h4>
                            <a class="btn btn-success col-3" href="{% url 'accounts:login' %}">
                                ログインページはこちら</a>
                            <h5>※アカウントを作成していない場合はこちらからサインアップをしてください。</h5>
                            <a class="btn btn-success col-3" href="{% url 'accounts:signup' %}">
                                サインアップはこちら
                            </a>
                            {% endif %}
                        </div>
                    </form>
                    

                </div>
            </div>
        </div>
    {% endblock %}

strategy/templates/index.html
{% extends 'base.html' %}

{% block title %}攻略情報投稿サイト{% endblock %}
{% block contents %}
{% include "strategy_title.html" %}
{% include "strategy_list.html" %}
{% include "pagination.html" %}
{% endblock %}

strategy/templates/mypage.html
{% extends 'base.html' %}
{% block title %}マイページ{% endblock %}
    {% block contents %}
    {% if user.is_authenticated %}
        <br>
        <div style="text-align: center">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{object_list.count}}</strong>件</p>
            {% endif %}
            <a href="{% url 'strategy:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}
    {% include "strategy_list.html" %}
    {% include "pagination.html" %}
    {% endblock %}

strategy/templates/post_success.html
{% extends 'base.html' %}
{% block title %}投稿成功！{% endblock %}
    {% block contents %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col offsett-2">
                <h4>投稿が完了しました！</h4>
            </div>
        </div>
    </div>
    {% endblock %}

strategy/templates/strategy_list.html
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for record in object_list %}
      <div class="col">
        <div class="card shadow-sm">
          <img src="{{ record.image1.url }}"
               class="bd-placeholder-img card-img-top" 
               width="100%" height="225" 
               xmlns="http://www.w3.org/2000/svg" 
               role="img" aria-label="Placeholder: Thumbnail" 
               preserveAspectRatio="xMidYMid slice" 
               focusable="false">
               <title>Placeholder</title>
               <rect width="100%" height="100%" fill="#55595c"/>
          </img>
          <div class="card-body">
            <p class="card-text">
              {{record.title}}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button"
                        class="btn btn-sm btn-outline-secondary"
                onclick="location.href='{% url 'strategy:strategy_detail' record.pk %}'">
                詳細</button>
                <button type="button" 
                        class="btn btn-sm btn-outline-secondary"
                onclick="location.href='{% url 'strategy:strategys_cat' category=record.category.id %}'">
                {{record.category.title}}</button>
              </div>
              <a href="{% url 'strategy:user_list' user=record.user.id %}">
                <small class="text-muted">
                  {{record.user.username}}</small>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

strategy/templates/strategy_title.html
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">攻略情報一覧</h1>
      <p class="lead text-muted">
        ゲームの攻略に関連するものを投稿や閲覧しましょう！！
        嘘偽りのない情報と優しいコメントをお待ちしております！</p>
      <p>
        {% if user.is_authenticated %}
        <a href="{% url 'strategy:post' %}" class="btn btn-primary my-2">投稿する</a>
        <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>